version: 0.2
 
phases:
  pre_build:
    commands:
      - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.4.deb
      - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.4.deb.sha512
      - shasum -a 512 -c elasticsearch-6.2.4.deb.sha512 
      - sudo dpkg -i elasticsearch-6.2.4.deb
      - sudo update-rc.d elasticsearch defaults 95 10
      - sudo -i service elasticsearch start
  build:
    commands:
      - mvn install
artifacts:
  files:
    - 'target/*'
    - 'aws/*'
  discard-paths: yes
  base-directory: distribution
