version: 0.2
 
phases:
  install:
    commands:
        - sudo apt-get install software-properties-common
        - sudo add-apt-repository ppa:openjdk-r/ppa
        - sudo apt-get update
        - sudo apt-get -y install openjdk-8-jdk
        - java -version
        - sudo apt-get -y install maven
        - mvn -version
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)        
  build:
    commands:
      - mvn install -DskipTests=true
      - docker build -t 306327466070.dkr.ecr.us-west-2.amazonaws.com/uvhub:$IMAGE_TAG ./UVHub/
      - docker build -t 306327466070.dkr.ecr.us-west-2.amazonaws.com/uvtracks:$IMAGE_TAG ./UVTracks/
      - docker build -t 306327466070.dkr.ecr.us-west-2.amazonaws.com/uvhub-test:$IMAGE_TAG ./UVHubTest/
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 306327466070.dkr.ecr.us-west-2.amazonaws.com/uvhub:$IMAGE_TAG     
      - docker push 306327466070.dkr.ecr.us-west-2.amazonaws.com/uvtracks:$IMAGE_TAG
      - docker push 306327466070.dkr.ecr.us-west-2.amazonaws.com/uvhub-test:$IMAGE_TAG 
cache:
  paths:
    - '/root/.m2/**/*'