/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE MISSION_CHANGED PACKING
package com.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
 * A broadcast message to notify any ground station or SDK if a mission, geofence or safe points have changed on the vehicle.
 */
public class msg_mission_changed extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_MISSION_CHANGED = 52;
    public static final int MAVLINK_MSG_LENGTH = 7;
    private static final long serialVersionUID = MAVLINK_MSG_ID_MISSION_CHANGED;

      
    /**
     * Start index for partial mission change (-1 for all items).
     */
    public short start_index;
      
    /**
     * End index of a partial mission change. -1 is a synonym for the last mission item (i.e. selects all items from start_index). Ignore field if start_index=-1.
     */
    public short end_index;
      
    /**
     * System ID of the author of the new mission.
     */
    public short origin_sysid;
      
    /**
     * Compnent ID of the author of the new mission.
     */
    public short origin_compid;
      
    /**
     * Mission type.
     */
    public short mission_type;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_MISSION_CHANGED;
        
        packet.payload.putShort(start_index);
        packet.payload.putShort(end_index);
        packet.payload.putUnsignedByte(origin_sysid);
        packet.payload.putUnsignedByte(origin_compid);
        packet.payload.putUnsignedByte(mission_type);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a mission_changed message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.start_index = payload.getShort();
        this.end_index = payload.getShort();
        this.origin_sysid = payload.getUnsignedByte();
        this.origin_compid = payload.getUnsignedByte();
        this.mission_type = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_mission_changed() {
        this.msgid = MAVLINK_MSG_ID_MISSION_CHANGED;
    }
    
    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_mission_changed( short start_index, short end_index, short origin_sysid, short origin_compid, short mission_type) {
        this.msgid = MAVLINK_MSG_ID_MISSION_CHANGED;

        this.start_index = start_index;
        this.end_index = end_index;
        this.origin_sysid = origin_sysid;
        this.origin_compid = origin_compid;
        this.mission_type = mission_type;
        
    }
    
    /**
     * Constructor for a new message, initializes everything
     */
    public msg_mission_changed( short start_index, short end_index, short origin_sysid, short origin_compid, short mission_type, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_MISSION_CHANGED;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.start_index = start_index;
        this.end_index = end_index;
        this.origin_sysid = origin_sysid;
        this.origin_compid = origin_compid;
        this.mission_type = mission_type;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_mission_changed(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_MISSION_CHANGED;
        
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

              
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_MISSION_CHANGED - sysid:"+sysid+" compid:"+compid+" start_index:"+start_index+" end_index:"+end_index+" origin_sysid:"+origin_sysid+" origin_compid:"+origin_compid+" mission_type:"+mission_type+"";
    }
    
    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_MISSION_CHANGED";
    }
}
        