/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
 * Possible values for COMPONENT_INFORMATION.comp_metadata_type.
 */
public class COMP_METADATA_TYPE {
   public static final int COMP_METADATA_TYPE_VERSION = 0; /* Version information which also includes information on other optional supported COMP_METADATA_TYPE's. Must be supported. Only downloadable from vehicle. | */
   public static final int COMP_METADATA_TYPE_PARAMETER = 1; /* Parameter meta data. | */
   public static final int COMP_METADATA_TYPE_COMMANDS = 2; /* Meta data which specifies the commands the vehicle supports. (WIP) | */
   public static final int COMP_METADATA_TYPE_ENUM_END = 3; /*  | */
}
            